- hosts: all
  sudo: True
  tasks:
  - name: Install bird ppa repository
    apt_repository: repo='ppa:cz.nic-labs/bird' state=present
  - name: Install Consul ppa repository
    apt_repository: repo='deb http://ppa.launchpad.net/bcandrea/consul/ubuntu trusty main' state=absent
  - template: src=roles/common/templates/policy-rc.d dest=/usr/sbin/policy-rc.d owner=root group=root mode=0755
  - name: run apt-get update on all nodes
    apt: update_cache=yes cache_valid_time=86400
  - name: Update pip
    pip: name=pip version=7.0.3

- hosts: router:hyp:bst
  sudo: True
  tasks:
  - name: Install bird routing daemon
    apt: name=bird state=present
    ignore_errors: True
  - name: Install unzip
    apt: name=unzip state=present
  - name: Download Consul binary file from local
    get_url: url=https://dl.bintray.com/mitchellh/consul/0.5.2_linux_amd64.zip dest=/tmp mode=0440
  - name: Unarchive Consul binary file
    unarchive: src=/tmp/0.5.2_linux_amd64.zip dest=/usr/local/bin copy=no
  - name: Create Consul folders
    file: path=/etc/consul state=directory mode=0755
    file: path=/etc/consul/consul.d state=directory mode=0755
  - name: Copy Consul upstart file
    template: src=roles/common/files/consul.conf dest=/etc/init owner=root group=root mode=0444
  - name: Copy Consul configuration file
    template: src=roles/common/templates/consul.conf.j2 dest=/etc/consul/consul.conf owner=root group=root mode=0444
  - name: Copy Bird config file
    template: src=roles/common/templates/bird.conf dest=/etc/bird/bird.conf owner=root group=root mode=0444
  - name: Start Consul
    service: name=consul state=started

- hosts: reg
  sudo: True
  tasks:
  - name: Install docker apt Key
    apt_key: keyserver=p80.pool.sks-keyservers.net id=36A1D7869245C8950F966E92D8576A8BA88D21E9
  - name: Install Docker rpository
    apt_repository: repo='deb https://get.docker.com/ubuntu docker main'
  - name: Run apt-get update
    apt: update_cache=yes
  - name: Install lxc-docker
    apt: name=lxc-docker state=present
  - name: remove docker init file (ansible manages init before upstrat)
    file: path=/etc/init.d/docker state=absent
  - name: Start Docker
    service: name=docker state=started
  - name: Install docker-py using pip
    pip: name=docker-py version=1.1.0 state=present
  - name: Create a user to run docker commands
    user: name=docker comment="Docker user" group=docker

- hosts: reg
  sudo: True
  sudo_user: docker
  tasks:
  - name: Start a Consul docker
    docker:
      name: consul-registry
      image: progrium/consul
      ports:
      - 53:53
      - 53:53/udp
      - 8300:8300
      - 8301:8301
      - 8301:8301/udp
      - 8400:8400
      - 8500:8500
      command: -node={{ ansible_nodename }} -advertise={{ ansible_eth0.ipv4.address }} -server -bootstrap -ui-dir /ui
      state: started
